codecov.yml

this is possibly why carryforward didn't work

fix incorrect key in codecov.yml

---

tools/absorb-repo/migrate-pr.sh

fix(migrate-pr.sh): missing space in reviewer args list

---

tools/livegrep/README.md
tools/livegrep/conf/livegrep.json
tools/livegrep/docker-compose.indexer.yml
tools/livegrep/docker-compose.yml

add sentry repos and separate index to livegrep configuration

---

.github/workflows/upload-overwatch.yml

Add overwatch step to umbrella repo

feat(overwatch): Add overwatch to umbrella

---

apps/codecov-api/webhook_handlers/views/github.py

Debugging webhook forwarding from shelter. Logging request info to identify whether codecov AI webhooks are being properly forwarded.

Update pull request webhook endpoint logs

---

apps/codecov-api/graphs/views.py

I added these metrics when I was assessing use - we no longer need all of them. Cleaned them up and gave them better names, which will leave us with summarized tracking and usage for flare graphs.
https://github.com/codecov/internal-issues/issues/1029

remove experimental metrics from GraphHandler

---

apps/worker/services/cleanup/pulls.py

This task is silently failing every time it is initialized - adding some things to help us figure out what's going wrong.

add debugging to flare cleanup task

---

apps/codecov-api/webhook_handlers/tests/test_github.py
apps/codecov-api/webhook_handlers/tests/test_github_enterprise.py
apps/codecov-api/webhook_handlers/views/github.py

Revert "remove deprecated integration stuff, simplify github install webhooks"

---

libs/shared/shared/reports/reportfile.py

Removing super spammy log statement that no one uses.

Remove unused logging

---

.github/workflows/upload-overwatch.yml

Point the download of the overwatch cli to the prod copy

chore(overwatch): Fix overwatch cli dl from prod

---

apps/worker/tasks/test_results_processor.py
apps/worker/tasks/tests/unit/test_test_results_processor_task.py

disabling this temporarily because it's getting in users' way and i didn't think about actionability when devising this

fix: disable warnings

---

pyproject.toml
uv.lock

see: https://github.com/jpadilla/pyjwt/issues/1017 for context
we're hitting the issue above in prod: https://codecov.sentry.io/issues/6639820689

build: pin JWT version to avoid breaking change for now

---

.github/workflows/push-stage.yml

This PR adds the build step to the staging workflow, otherwise we don't have an image to reference (lol)

fix: Add build step to stage deploy workflow

---

apps/worker/services/cleanup/pulls.py
apps/worker/services/cleanup/tests/test_pulls.py

full send. all gas no brakes. 🚀 🚀 🚀

remove hard-coded limits on flare cleanup nightly task

---

apps/codecov-api/webhook_handlers/tests/test_github.py
apps/codecov-api/webhook_handlers/views/github.py

Had some regrets - don't want this to get lost in a sea of logs, this situation is unexpected and should be louder if it happens.

send to sentry not gcp

---

apps/worker/services/test_analytics/ta_process_flakes.py

this should avoid us scanning a bunch of irrelevant hypertable partitions

perf: attempt to improve perf of proc flakes query

---

libs/shared/shared/django_apps/db.py
libs/shared/shared/django_apps/ta_timeseries/models.py

Sentry has this in their repo and I think it's pretty nifty so I'm adding it here for now

feat: create and add sane_repr to TA models

---

apps/codecov-api/services/task/task.py
apps/worker/app.py
apps/worker/tasks/__init__.py
apps/worker/tasks/tests/unit/test_upload_breadcrumb.py
apps/worker/tasks/upload_breadcrumb.py
libs/shared/shared/celery_config.py
libs/shared/shared/django_apps/upload_breadcrumbs/models.py
libs/shared/shared/utils/pydantic_serializer.py
libs/shared/tests/unit/utils/test_pydantic_serializer.py

* Celery task for creating upload breadcrumb objects
* Pydantic model support for Celery tasks

feat: Upload breadcrumb task

---

apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_test_results_timescale_empty_parameter__0.json
apps/codecov-api/graphql_api/tests/test_test_analytics_timescale.py
apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py

this was causing an error if filters was set and parameters was not, the type ignore was hiding this

fix: not checking if parameter is None in TA GQL

---

apps/codecov-api/utils/timescale_test_results.py

some light refactoring and typing fixes to make subsequent changes easier

ref: timescale test results file

---

README.md
tools/devenv/Makefile.test

* New all in one make upload command
* Document both the test and upload all in one commands
* Give code blocks shell formatting

feat(devenv): Make `upload` command and documentation

---

apps/worker/tasks/cache_test_rollups.py
apps/worker/tasks/process_flakes.py

otherwise if the new impl fails, we'll crash and never get to the old impl

fix: wrap new TA impl in try except for cache rollups

---

tools/devenv/Makefile.devenv

This improves the clarity of the admin command instructions
Thanks to @jason-ford-codecov for the suggestion :)

chore(devenv): Add an explicit URL to the main application

---

apps/worker/database/models/reports.py
apps/worker/django_scaffold/settings_prod.py
apps/worker/services/test_analytics/ta_finish_upload.py
apps/worker/services/test_analytics/ta_timeseries.py
apps/worker/services/test_results.py
apps/worker/tasks/__init__.py
apps/worker/tasks/test_analytics_notifier.py
apps/worker/tasks/tests/unit/test_test_analytics_notifier.py
libs/shared/shared/celery_config.py
libs/shared/shared/django_apps/settings_test.py
libs/shared/shared/django_apps/ta_timeseries/tests/factories.py

Depends on #418 and #421 
* Resolved some pytest warnings due to class names
* Added Sentry app name setting to worker prod and shared testing
* Added the new TA notifier task

feat(worker): New TA notifier task

---

apps/codecov-api/graphql_api/tests/mutation/test_sync_repos.py
apps/codecov-api/graphql_api/types/mutation/sync_repos/sync_repos.py

Revert "feat(Prevent): return the refreshing value for the is_syncing key"

---

apps/worker/services/test_analytics/ta_finish_upload.py
apps/worker/services/test_analytics/ta_timeseries.py
apps/worker/services/test_analytics/tests/test_ta_timeseries.py

without a lower bound on the timestamp, Timescale decides to check every chunk
of data, which is really expensive. If we can give a lower bound to where we
think the data might be, it'll speed up queries because Timescale will know it
doesn't have to check certain chunks.
I tested this for a given query and we went from
55 ms (40 planning + 15 execution) to 5ms (4 planning + 1 execution)
that specific query is the 3rd highest in time spent in the last 24 hours
according to Sentry's query insights

feat: add lower bound to get_pr_comment TA functions

---

apps/codecov-api/codecov_auth/middleware.py
apps/codecov-api/codecov_auth/tests/test_middleware.py
apps/codecov-api/graphql_api/tests/test_sentry_view.py
tools/devenv/Makefile.test

This PR prefetches the user when getting the owner so it doesn't have to prefetch it later. Ultimately a DB enhancement

feat: prefetch user for sentry endpoint

---

apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__3.txt
apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__4.txt
apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__5.txt
apps/worker/services/test_results.py
apps/worker/services/tests/snapshots/results__build_message__0.txt
apps/worker/services/tests/snapshots/results__build_message_with_flake__0.txt

we need to update the link because there's a new form :)

fix: update feedback form in TA PR comment

---

apps/codecov-api/utils/ta_timescale/test_results.py

we weren't casting this which meant that the operation was ending up as an int which meant that we were showing the wrong result in the UI

fix: flake rate and failure rate in UI now show the right numbers

---

apps/codecov-api/api/sentry/tests/test_views.py
apps/codecov-api/api/sentry/views.py

Revert "fix: Account link should respect existing owners seat counts"
