codecov/umbrella

- .github/workflows/api-ci.yml
- .github/workflows/worker-ci.yml
there is just no way to test this stuff. irritating
because the job wasn't in the `needs` list, trying to get its output silently returns ""
this should fix failing "Build Self-hosted App" steps in umbrella CI
> fix: add missing "needs" declaration to self-hosted actions in ci

- libs/shared/.gitignore
it would make sense to merge all three projects' `.gitignore` into a top-level `umbrella` one but that's a different commit
> fix: add shared test junit/coverage artifacts to gitignore

- apps/codecov-api/services/bundle_analysis.py
- apps/codecov-api/upload/helpers.py
- apps/codecov-api/upload/tests/test_upload.py
- apps/codecov-api/upload/views/bundle_analysis.py
- apps/codecov-api/upload/views/legacy.py
- apps/codecov-api/upload/views/test_results.py
- apps/codecov-api/upload/views/uploads.py
- apps/worker/tasks/tests/integration/test_upload_e2e.py
- apps/worker/tasks/tests/unit/test_preprocess_upload.py
- apps/worker/tasks/tests/unit/test_upload_task.py
- apps/worker/tasks/upload.py
This removes some `report_code` usage where it is not being used.
It also simplifies the `disptach_upload_task` fn a bit, which I just couldn’t resist :-D
> Clean up some `report_code` usage

- docker-compose.yml
- docker/init_db.sql
- tools/devenv/Makefile.devenv
- tools/devenv/scripts/start-worker.sh
we need to:
- create the TA db in timescale
- run the migrate_timeseries.py script to apply migrations
> build: run TA timeseries migrations

- Makefile
I've been having problems building the requirements images since fetching the debian or cargo reqs will randomly fail, building with the host network fixes that
> docker: build with host network

- apps/codecov-api/api/internal/repo/views.py
if [`RepositoryViewSetMixin.check_object_permissions()`](https://github.com/codecov/umbrella/blob/595af92059db4c6e7dba591fee0a905e28d96f4a/apps/codecov-api/api/shared/repo/mixins.py#L44) has not been called, the `self.can_edit` and `self.can_view` attributes don't exist and this code blows up. this code uses `getattr` with a default value of `False`
this "mixins" pattern is strange to me. a mixin doesn't appear to have a way to initialize its instance state when an object is constructed, so if things outside the mixin try to use that state before calling a magic function it will blow up. i think the safe thing to do would be for the mixin to only expose state through getters which lazy-initialize?
> fix: use getattr in RepositoryViewSet to handle attrs that may not be set

- apps/worker/services/cleanup/uploads.py
Now that the cleanup has been changed to work on chunks, it seems to run fine.
Except that there was a bug and I was overwriting / shadowing the `query` variable. So the cleanup was only running a single iteration of the chunk cleanup loop.
> Fix old upload cleanup

- apps/codecov-api/services/task/task.py
- apps/codecov-api/upload/helpers.py
- apps/codecov-api/upload/serializers.py
- apps/codecov-api/upload/tests/test_upload.py
- apps/codecov-api/upload/tests/views/test_base.py
- apps/codecov-api/upload/tests/views/test_bundle_analysis.py
- apps/codecov-api/upload/tests/views/test_reports.py
- apps/codecov-api/upload/tests/views/test_test_results.py
- apps/codecov-api/upload/tests/views/test_upload_coverage.py
- apps/codecov-api/upload/tests/views/test_uploads.py
- apps/codecov-api/upload/views/base.py
- apps/codecov-api/upload/views/bundle_analysis.py
- apps/codecov-api/upload/views/reports.py
- apps/codecov-api/upload/views/test_results.py
- apps/codecov-api/upload/views/uploads.py
- apps/worker/services/bundle_analysis/report.py
- apps/worker/services/report/__init__.py
- apps/worker/services/test_results.py
- apps/worker/tasks/manual_trigger.py
- apps/worker/tasks/preprocess_upload.py
- apps/worker/tasks/tests/unit/test_manual_trigger.py
- apps/worker/tasks/tests/unit/test_preprocess_upload.py
- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
- apps/worker/tasks/tests/unit/test_upload_task.py
- apps/worker/tasks/upload.py
- apps/worker/tasks/upload_finisher.py
This removes all the places where a non-default `report_code` is being passed around and used. It also changes the view serializer to reject any non-"default" `code` as well.
> Fully remove and disallow non-default `report_code`

- .github/workflows/enforce-license-compliance.yml
i am trying a tool that stacks PRs and i need this workflow to run for everything in the stack
- https://github.com/codecov/umbrella/pull/87 was based on main
- https://github.com/codecov/umbrella/pull/88 was based on the above
- https://github.com/codecov/umbrella/pull/89 was based on the above
- https://github.com/codecov/umbrella/pull/90 was based on the above
each one needs this job to trigger
> remove branch filter for PRs in enforce-license-compliance.yml

- libs/shared/shared/torngit/github.py
Prevent the error log that occurs when token refresh fails from bubbling up to Sentry.
Resolves https://codecov.sentry.io/issues/4530397997/events/ab8faf32f54247a9a3c9fac416a7a757/
> chore: suppress Sentry error from token refresh failure

- Makefile
what an irritating bug
with this fixed, your mac should come up with the same requirements image tags as CI. with this + https://github.com/codecov/umbrella/pull/101 you should be able to pull prebuilt recs images and speed up your local dev experience
> fix: add LC_ALL=C to makefile sort usage to normalize order

- apps/codecov-api/codecov_auth/tests/test_admin.py
- apps/codecov-api/graphql_api/tests/test_test_analytics.py
- apps/codecov-api/upload/tests/test_serializers.py
- apps/worker/services/report/tests/unit/test_transplant.py
- apps/worker/services/test_analytics/ta_process_flakes.py
- apps/worker/services/test_analytics/tests/test_ta_process_flakes.py
- apps/worker/services/test_analytics/tests/test_ta_processor.py
- apps/worker/services/tests/test_report.py
- apps/worker/tasks/tests/integration/test_upload_e2e.py
- apps/worker/tasks/tests/unit/test_base.py
- apps/worker/tasks/tests/unit/test_cache_rollup_cron_task.py
- apps/worker/tasks/tests/unit/test_cache_test_rollups.py
- apps/worker/tasks/tests/unit/test_cache_test_rollups_redis.py
- apps/worker/tasks/tests/unit/test_delete_owner.py
- apps/worker/tasks/tests/unit/test_flare_cleanup.py
- apps/worker/tasks/tests/unit/test_notify_task.py
- apps/worker/tasks/tests/unit/test_preprocess_upload.py
- apps/worker/tasks/tests/unit/test_process_flakes.py
- apps/worker/tasks/tests/unit/test_sync_repos_task.py
- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
- apps/worker/tasks/tests/unit/test_upload_processing_task.py
- apps/worker/tasks/tests/unit/test_upload_task.py
- apps/worker/tasks/upload.py
- libs/shared/tests/integration/test_bots.py
- libs/shared/tests/integration/test_github.py
- libs/shared/tests/unit/bots/test_bots.py
- libs/shared/tests/unit/bots/test_github_apps.py
- libs/shared/tests/unit/django_apps/test_model_utils.py
- libs/shared/tests/unit/rate_limits/test_rate_limit.py
- libs/shared/tests/unit/torngit/test_github.py
Similar to the case with `TransactionTestCase`, the `transactional_db` might be a bit slower, as is has to do more heavy lifting to setup/teardown the test. So lets switch to regular testcases, hopefully speeding up the tests slightly.
> Switch some `transactional_db` fixtures to `db`

- apps/worker/services/cleanup/regular.py
- apps/worker/services/cleanup/tests/test_regular_cleanup.py
As we are deprecating the "staticanalysis" (aka ATS [automated test selection]) and the "local-upload" (aka `report_code`) features, this adds the related models (`StaticAnalysisSingleFileSnapshot` and `CommitReport` with a `code`) to the cleanup task.
Thus, all related files in storage, and database entities will be cleaned up.
> Cleanup `staticanalysis` and `local-upload` related entities

- apps/codecov-api/webhook_handlers/views/github.py
Shelter is forwarding these webhooks but we do not seem to be consuming them properly, adding logs to debug. Will revert once a solution is identified.
> [api] Add debug logs for codecov AI app checks

- apps/codecov-api/services/comparison.py
Bringing parity with https://github.com/codecov/codecov-api/pull/1297
> [fix] Fix segments error

- libs/shared/shared/rollouts/__init__.py
this fires constantly and makes logs much less useful
> chore: remove log that is extremely noisy in dev envs

- .github/workflows/ci-router.yml
- docker-compose.yml
required checks are based on the name so before i make the lint check required i should fix the typo
also i originally made `worker` depend on `api` in `docker-compose.yml` so that the latter would run migrations first. turns out that didn't work and they still raced, so now there is `make devenv.migrate`. this PR removes that dependency which will slightly improve startup and teardown time
> fix: typo in lint CI name and unnecessary docker-compose dep

- apps/worker/services/cleanup/cleanup.py
- apps/worker/services/cleanup/models.py
- apps/worker/services/cleanup/owner.py
- apps/worker/services/cleanup/regular.py
- apps/worker/services/cleanup/repository.py
- apps/worker/services/cleanup/tests/test_regular_cleanup.py
- apps/worker/services/cleanup/tests/test_upload_cleanup.py
- apps/worker/services/cleanup/uploads.py
- apps/worker/services/cleanup/utils.py
- apps/worker/tasks/flare_cleanup.py
- apps/worker/tasks/tests/unit/test_delete_owner.py
- apps/worker/tasks/tests/unit/test_flare_cleanup.py
- apps/worker/tasks/tests/unit/test_flush_repo.py
This improves regular cleanup scheduling by integrating queryset-based cleanups with fn-based ones.
The progress reporting is changed in such a way that progress is logged regularly in a debounced fashion, as well as logging a summary once the contextmanager either finished regularly, or is being aborted due to a timeout.
> Improve cleanup progress reporting and scheduling

- docker-compose.yml
This option only really exists for self-hosted customers to manually toggle this feature in the case they don't want to deploy timescale, which will soon be required for TA. However when we're deploying locally, we always want to be running TA, so i'm enabling this by default in the devenv so that it works out of the box.
> build: enable ta timeseries by default in devenv

- apps/codecov-api/codecov_auth/commands/owner/interactors/get_is_current_user_an_admin.py
we seem to be running into an error here on prod, we don't want to break the previous behaviour of this function but we want insight into the error so we'll just capture the exception manually
> fix: capture exception in is admin interactor

- tools/devenv/scripts/start-worker.sh
https://github.com/codecov/umbrella/pull/72 invokes this script in two different ways. this way is apparently wrong so i changed it to the other way
> fix: use correct invocation of migrate_timeseries.py in devenv startup

- apps/worker/services/bundle_analysis/notify/contexts/tests/test_comment_context.py
- apps/worker/services/bundle_analysis/notify/contexts/tests/test_commit_status_context.py
- apps/worker/services/tests/test_repository_service.py
- apps/worker/services/tests/unit/test_archive_service.py
- apps/worker/tasks/tests/unit/test_upload_processing_task.py
Running tests with a different (invalid) `config/codecov.yaml` revealed a bunch of tests that are initializing (but not necessarily using) the `ArchiveService`.
I have added the `mock_storage` fixture to those tests, to make sure any test that touches storage (except tests for storage itself) are going through the mock.
> Add `mock_storage` to a bunch more places

- apps/codecov-api/services/tests/test_billing.py
this test reliably fails locally for me:
```
E           AssertionError: expected call not found.
E           Expected: error('Unable to update billing address for customer', extra={'customer_id': '123', 'subscription_id': '123', 'error': 'Invalid API Key provided: default', 'error_type': 'AuthenticationError'})
E             Actual: error('Unable to update billing address for customer', extra={'customer_id': '123', 'subscription_id': '123', 'error': "Request req_ZQjaUYHnNvMoK5: No such customer: '123'", 'error_type': 'InvalidRequestError'})
```
this PR definitely doesn't fix it but it should get it passing again at least.
there are two significant problems with this test and i don't know enough about this code to actually fix it:
- currently it asserts that stripe should not have an API …
> fix(api): semi-fix broken billing test to get it passing again

- apps/codecov-api/graphql_api/types/owner/owner.py
when resolving the activated user in GQL, if the current owner is a Gitlab owner we should check if the user is in the plan activated users of the root org since the subgroup doesn't seem to contain that information
the other option here is to actually add the relevant users to the subgroup owner in the db, but this seems like the shorter fix to unblock customers even though it may be the less correct one
> fix: use root org for activated user

- apps/worker/main.py
- apps/worker/tests/unit/test_main.py
- Update the logic to conditionally prepend "enterprise_" to queue names only if they do not already start with it, based on the `enterprise_queues_enabled` configuration.
- Add tests to verify behavior when enterprise queues are disabled and ensure no duplication of enterprise prefixes in the input.
> Enhance queue parameter handling in `_get_queues_param_from_queue_input`

- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/tests/test_github_enterprise.py
- apps/codecov-api/webhook_handlers/views/github.py
removing the deprecated integration flow means these two webhook events could be simplified.
modified them to share a `handle` function
> remove deprecated integration stuff, simplify github install webhooks

- apps/worker/rollouts/__init__.py
- apps/worker/services/test_analytics/ta_processor.py
- apps/worker/services/test_analytics/ta_timeseries.py
- apps/worker/services/test_analytics/tests/test_ta_vitest_evals.py
- apps/worker/tasks/tests/integration/test_upload_e2e.py
This is just a temporary solution to ingest and store evals metadata, before we have this properly standardized/implemented as a junit xml extension.
Eventually, we want to display this metadata as part of the PR comment.
---
The example snippet comes from https://github.com/getsentry/vitest-evals/issues/13#issuecomment-2835687888, first step of https://github.com/codecov/test-results-action/issues/120
> Implement consuming `vitest` json with `evals` metadata

- libs/shared/shared/bundle_analysis/models.py
This solves a sqlalchemy deprecation warning.
> Import `declarative_base` from different module

- apps/codecov-api/pyproject.toml
- apps/codecov-api/uv.lock
- apps/worker/pyproject.toml
- apps/worker/uv.lock
- libs/shared/pyproject.toml
- libs/shared/uv.lock
We still had to keep `types-request` pinned to a lower version, because it depends on `urllib3>=2`, which itself conflicts with `vcrpy` which depends on `urllib3<2`.
---
The situation with `urllib3` is quite unfortunate. Seems like `vcrpy` is the one to blame here, as it depends on an outdated version explicitly.
> Update all `dev-dependencies` as high as possible

- apps/codecov-api/codecov/settings_test.py
- apps/codecov-api/codecov_auth/middleware.py
- apps/codecov-api/codecov_auth/tests/test_middleware.py
- apps/codecov-api/graphql_api/tests/test_sentry_view.py
- apps/codecov-api/graphql_api/urls.py
- apps/codecov-api/graphql_api/views.py
This change adds a new middleware to process the JWT authentication for communicating with Sentry. It also adds a new GraphQL endpoint that uses this middleware for authentication (shouldn't affect existing endpoint).
This assumes the JWT claim to look something like:
```
{
'g_u': 'github_service_id',
'g_p': 'github',
}
```
> Add JWT Middleware authentication with endpoint

- apps/codecov-api/codecov_auth/middleware.py
- apps/codecov-api/codecov_auth/tests/test_middleware.py
- apps/codecov-api/codecov_auth/utils.py
- apps/codecov-api/graphql_api/tests/test_sentry_view.py
- apps/codecov-api/webhook_handlers/permissions.py
- apps/codecov-api/webhook_handlers/tests/test_jwt_permissions.py
This change adds the JWT auth check for Sentry requests. It also removes the user/provider claims requirements, as it's not required for webhook requests.
This is specifically for Webhooks, but does not add the Webhook API endpoint.
> Add JWT permissions to Django REST Framework

- apps/codecov-api/codecov_auth/admin.py
small change to help anyone using the admin to change plan or seats
preview:
> Make Accounts more apparent on Owner admin

- .github/workflows/_build-requirements.yml
- .github/workflows/shared-ci.yml
- Makefile
- ci-tests.docker-compose.yml
- codecov.yml
- docker-compose.yml
- docker/Dockerfile.requirements
- docker/Makefile.ci-tests
- libs/shared/docker/Dockerfile
- tools/devenv/Makefile.devenv
more cleanup. moves closer towards a monolith
<details open><summary> Stack info:</summary>
| Stack 1 |
|-|
|<ul><li>https://github.com/codecov/umbrella/pull/167</li><li>https://github.com/codecov/umbrella/pull/168</li><li>https://github.com/codecov/umbrella/pull/169</li><li>➡️https://github.com/codecov/umbrella/pull/170</li></ul>|
</details>
> build: make shared use the same makefile and ci setup as worker/api

- libs/shared/tests/unit/test_config.py
When running the local development environment, `SETUP__TA_TIMESERIES__ENABLED` gets set in `docker-compose.yml` which this test includes in the returned config and causes it to fail. Adding the clear option ensures that only the expected mock environment variables get used for the test.
> fix(shared): Clear environment to reduce flakiness from external variables

- .github/workflows/shared-ci.yml
CodSpeed does not yet support merge queues (https://github.com/CodSpeedHQ/action/issues/126) so this reduces the resulting false failures.
Example of one such failure: https://github.com/codecov/umbrella/actions/runs/15303668976/job/43050709204
> ci(shared): Skip CodSpeed benchmark on `merge_group`

- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
TestUploadFinisherTask::test_upload_finisher_task_call fails on my local but passes on ci runs
> add redis mock to test that fails locally

- .github/workflows/api-ci.yml
- .github/workflows/ci-router.yml
- .github/workflows/push-stage.yml
- .github/workflows/worker-ci.yml
This PR creates a new job called push-stage.yml which will auto push images to stage if we push to the staging branch. It skips tests, shared stuff, lint, etc so we can get our changes as quick as possible.
This fixes a bug where stage and main might be on the same hash and thus, no changes would be detected if we wanted main and staging to be the same. Previously we thought to just add some conditionals to the ci-router.yml but decided to create a new job altogether via @matt-codecov's suggestion
> feat: separate stage workflow for ci / deploys

- docker-compose.yml
"exposing" the port makes the container listen on that port internally without binding any ports on the host machine. we don't actually need/want port 8000 on the host bound to the api because we can access it through codecov-gateway on port 8080
EDIT: apparently "expose" makes API non-responsive in my local CC instance so i changed back to "ports" but am only supplying the container's port. it will bind to a random host port
> fix: make docker-compose.yml "expose" api port internally instead of binding to host port

- .github/workflows/ci-router.yml
- .github/workflows/push-stage.yml
this PR makes `push-stage.yml` wait for `worker-ci.yml` and `api-ci.yml` to run before running. otherwise, it will trigger a whole bunch of duplicated image-building work:
- it will build a worker image while `worker-ci.yml` is also building one
- it will build an api image while `api-ci.yml` is also building one
- it will not wait on `_build-requirements.yml`, so both of the above images will also build (but not cache) the requirements image
this PR waits until `worker-ci.yml` and `api-ci.yml` have run before kicking off `push-stage.yml` so that it can reuse the images they built, and it uses `always()` to run regardless of whether the tests passed in those workflows
> ci: change how push-stage.yml job is run

- apps/codecov-api/api/gen_ai/tests/test_gen_ai.py
- apps/codecov-api/api/gen_ai/views.py
We use this endpoint to validate that a user has the Codecov AI app installed before initiating any Seer workflows. It's possible for multiple owners to have the same service ID so there were cases where we were not fetching the right owner. This change fixes that.
> [fix] Add github service filter check to Gen AI auth

- apps/worker/conftest.py
- apps/worker/main.py
- apps/worker/services/test_analytics/tests/test_ta_processor.py
- apps/worker/tasks/tests/integration/test_notify_task.py
- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
- apps/worker/tests/unit/test_main.py
- libs/shared/shared/storage/memory.py
- libs/shared/tests/unit/storage/test_memory.py
stop doing the "initialize django in the middle of our imports and disable all the lints that get mad" thing, and get rid of the `print()` that we do because our log initialization was sloppy
there is still a stupid import hack, but it's confined to `test_main.py` and is specifically for asserting on the thing that used to be a `print()`
<details open><summary> Stack info:</summary>
| Stack 1 |
|-|
|<ul><li>https://github.com/codecov/umbrella/pull/214</li><li>➡️https://github.com/codecov/umbrella/pull/215</li></ul>|
</details>
> refactor: clean up worker initialization

- apps/codecov-api/graphql_api/types/enums/upload_error_enum.graphql
- apps/codecov-api/graphql_api/types/upload/upload.py
- libs/shared/shared/upload/constants.py
we don't want unknown error codes to cause exceptions so i'm adding an unkown_error_code variant to the enum that we can fallback to when we encounter an error code
the frontend components that encounter an unknown error code should probably ignore it most of the time, it will probably signify error codes that are only relevant to backend components and thus don't get a dedicated variant in the UploadErrorEnum gql type
> fix: error code gql resolver

- apps/worker/tasks/test_results_processor.py
- apps/worker/tasks/tests/unit/test_test_results_processor_task.py
Previously if the new TA processor was failing while in both mode, we would crash the entire test results processor task, but we want to have the old implementation still run even if the new one fails, so this fixes that.
> fix: handle new TA task failures gracefully

- .github/workflows/push-stage.yml
Updates the stage action name for worker deploy image to match what hooky is expecting.
https://github.com/codecov/hooky/blob/0ece194f56d09b237d983f4e009f4ab27b59ec2e/app/Services/GithubService.php#L520-L523
> fix: Use hooky name in stage action

- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/tests/test_github_enterprise.py
- apps/codecov-api/webhook_handlers/views/github.py
Final (?) part in tackling race conditions in the GH install webhooks! 
The `unique_together` I created, plus the update to the `get_or_create` means django will handle any collisions gracefully.
previous attempt (https://github.com/codecov/umbrella/pull/85) was merged and reverted, then I did several migrations (https://github.com/codecov/umbrella/pull/171, https://github.com/codecov/umbrella/pull/219) to clean up and make the database into source of truth.
> install webhooks race condition

- apps/codecov-api/graphql_api/tests/actions/test_commits.py
This test has previously been flaky due to the randomness in the order that `repo_commits` may return. Using sets instead of lists fixes this issue.
> fix(api): Use sets instead of lists to prevent reordering flakiness

- apps/codecov-api/codecov/settings_base.py
- apps/codecov-api/codecov/settings_dev.py
- apps/codecov-api/codecov/settings_enterprise.py
- apps/codecov-api/codecov/settings_prod.py
- apps/codecov-api/codecov/settings_staging.py
- apps/codecov-api/codecov_auth/middleware.py
- apps/codecov-api/codecov_auth/tests/unit/test_middleware.py
- apps/codecov-api/codecov_auth/tests/unit/views/test_base.py
- apps/codecov-api/codecov_auth/tests/unit/views/test_gitlab.py
- apps/codecov-api/codecov_auth/tests/unit/views/test_okta_cloud.py
Our API currently adds the `Access-Control-Allow-Credentials` header to requests originating from our whitelisted domains and sets `Access-Control-Allow-Origin` to the request origin for **all requests**. This is misleading since it implies every origin is on our whitelist and it risks us accidentally setting `Access-Control-Allow-Credentials` on non-whitelisted origins (whereas setting `Access-Control-Allow-Credentials` is a specification violation if `Access-Control-Allow-Origin` is set to `*`). To this point, we have received two security reports about our CORS configuration, where the researchers assume we have unintentionally allowed requests from every domain.
This PR fixes the issue by leaving credentials and standard origin headers to the base CORS module and then based on a …
> fix: CORS custom logic returns `*` for external origins

- docker-compose.yml
The default Minio port is 9000, so we need to override it. Additionally, we want our development environment to use the latest gateway version, instead of waiting for explicit releases.
> fix: Override default Minio port and use rolling gateway image

- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/views/github.py
The `deactivate_user` function also gives us the side effect of updating associated accounts as well. We should be using this.
> Use the correct user removal for webhooks remove

- .github/workflows/ci-router.yml
as-is you can totally break our `Makefile`s and CI workflows and required checks will all be skipped and you can merge. that's not good
> [!Note]
> if there are CI failures when you look at this, they're because i created https://github.com/codecov/umbrella/pull/188 first and this PR is using that one's cached images without the rest of its changes. there is no actual breakage. the only change here is to run CI more often.
<details open><summary> Stack info:</summary>
| Stack 1 |
|-|
|<ul><li>https://github.com/codecov/umbrella/pull/186</li><li>https://github.com/codecov/umbrella/pull/187</li><li>➡️https://github.com/codecov/umbrella/pull/190</li><li>https://github.com/codecov/umbrella/pull/188</li></ul>|
</details>
> build: trigger all tests when reqs and build glue are changed

- .dockerignore
- .github/workflows/_build-app.yml
- .github/workflows/_build-requirements.yml
- .github/workflows/_run-tests.yml
- .github/workflows/ci-router.yml
- ci-tests.docker-compose.yml
- docker/Dockerfile.requirements
- docker/Dockerfile.test-requirements
- docker/Makefile.ci-tests
- docker/Makefile.docker
- docker/README.md
- pyproject.toml
- tools/devenv/Makefile.devenv
- tools/devenv/Makefile.test
as title
this should clean up our production image as well as save some CI time. as-is, _every_ CI run for worker, api, and shared all must run `apt-get install ...` and `pip install ...` to install the same junk inside the container. this PR caches that junk so all that must be done most of the time is copying the repo into the image
further changes are possible. all three test images are essentially identical; we could just build/publish a generic test image and override the workdir and entrypoint in docker-compose. i may try to do basically that for our production images.
<details open><summary> Stack info:</summary>
| Stack 1 |
|-|
|<ul><li>https://github.com/codecov/umbrella/pull/186</li><li>https://github.com/codecov/umbrella/pull/187</li><li>https://github.com/codecov/umbrella/pull/ …
> build: remove dev deps from prod image, add separate test-reqs and test-app images

- apps/codecov-api/codecov/settings_base.py
- apps/codecov-api/codecov_auth/middleware.py
- apps/codecov-api/codecov_auth/tests/unit/test_middleware.py
We previously did not return the `Access-Control-Allow-Headers`, `Access-Control-Allow-Methods`, and `Access-Control-Max-Age`, headers on `OPTIONS` requests coming from an external (non-whitelisted domain). With this change, we properly allow for 3rd parties to use our API with CORS-enabled requests.
Shout out to @spalmurray for pointing out the missing headers.
> fix(api): Add missing CORS headers on external `OPTIONS` requests

- libs/shared/shared/django_apps/db_settings.py
- libs/shared/shared/django_apps/utils/partitioning.py
Move the Postgres partition management definitions into a shared location and correct associated comments.
Note that I tested that the `pgpartition` command still works in staging
> refactor(shared): Centralize Postgres partition location

- apps/worker/celery_config.py
- apps/worker/tasks/__init__.py
- apps/worker/tasks/partition_management.py
- apps/worker/tasks/tests/unit/test_partition_management_task.py
- libs/shared/shared/celery_config.py
- libs/shared/shared/utils/enums.py
- libs/shared/tests/unit/test_celery_config.py
This Celery task ensures that partitions are automatically managed (created and deleted) instead of relying on startup scripts running on new deploys.
> feat: Celery task to run `pgpartition` on a schedule

- apps/codecov-api/api/public/v2/evals/views.py
- apps/codecov-api/api/public/v2/tests/test_api_evals_viewset.py
- pyproject.toml
- uv.lock
and make the aggregation endpoint a bit more flexible in terms of what `Testrun.properties` can be
> update test-result-parser to parse evals info out of JUnit

- apps/codecov-api/utils/test_results.py
divisions by zero, e.g. avg duration calculation where the total tests is 0, are causing NaNs to show up in the polars dataframe
the NaNs are causing errors in the GQL API which leads to the UI not even displaying, this only happens when we try to return values with NaNs 
also this error is isolated to users reading from the new TA rollups which is just us for now
> fix: TA ordering and filtering bug

- apps/codecov-api/graphql_api/tests/test_test_analytics.py
- apps/codecov-api/utils/test_results.py
I added functionality in the worker previously to enable the "new" impl_type for repos that started uploading after a specific cutoff date since we didn't need to wait for data to backfill into timescale.
I failed to match that change here, so users were only writing to timescale on the worker side but trying to read from the old rollups on the API side.
this commit fixes this issue by checking the cutoff date alongside the feature flag.
> fix: add cutoff date to TA dashboard read path

- libs/shared/shared/django_apps/codecov_auth/migrations/0070_add_sentry_merge_plan.py
Production migration does not have the correct permissions to do the plan migration. Turning this migration into a risky one to skip the migration. We would need to run this migration seperately.
> Skip migrating risky plans change

- README.md
- apps/codecov-api/README.md
- apps/worker/.envrc
- apps/worker/README.md
- apps/worker/tasks/base.py
- libs/shared/README.md
- tools/devenv/Makefile.test
* Remove extra `Makefile` newline
* Remove old `.envrc` file
* Move the `psycopg2` import back into the `try...except` out of caution (was originally moved in #249)
* Move the contributors section to the main read
* Update `shared` module instructions for the monorepo setup
> chore: Documentation and misc cleanup

- apps/codecov-api/conftest.py
we're getting the deadlock error in the API tests, the reason is that Timescale index creations deadlock with continuous aggregate refreshes like so:
```
2025-07-04 18:28:32.940 UTC [60026] DETAIL:  Process 60026 waits for AccessShareLock on relation 30135 of database 30126; blocked by process 60008.
Process 60008 waits for ShareLock on relation 30150 of database 30126; blocked by process 60026.
Process 60026: CALL _timescaledb_internal.policy_refresh_continuous_aggregate()
Process 60008: 
CREATE INDEX IF NOT EXISTS ta_ts_testrun_summary_repo_id_ts_bin_idx
ON ta_timeseries_testrun_summary_1day (repo_id, timestamp_bin DESC);
```
so we have to disable the background worker while we run the migrations for tests
this PR takes overwrites the django_db_setup fixture and adds some statements to …
> test: disable TS background worker during migrations

- README.md
- apps/worker/README.md
- tools/devenv/Makefile.test
Title, adds to API, Shared, and Worker
Closes https://linear.app/getsentry/issue/CCMRG-1055/extra-pytest-args-variable-in-toolsdevenvmakefiletest
> feat: Add pytest path variable for running pytest with a path

- apps/worker/services/test_analytics/ta_process_flakes.py
we were only setting this outcome to flaky failure if we were creating a new flake, but any failure on the main branch should be considered a flaky failure (by our heuristic) so to be _correct_ we should be setting the outcome to flaky no matter if it 's for an existing flake or a new flake
a scenario where this would have been broken is if we had 2 uploads in quick succession and the flake weren't created by the first upload by the time we were processing the tests in the second, in this case we'd be missing a flaky test outcome on the second testrun
> fix: always set testrun outcome to flaky_failure in process flakes

- apps/codecov-api/codecov_auth/commands/owner/interactors/trigger_sync.py
- apps/codecov-api/codecov_auth/commands/owner/owner.py
- apps/codecov-api/graphql_api/tests/mutation/test_sync_repos.py
- apps/codecov-api/graphql_api/types/mutation/__init__.py
- apps/codecov-api/graphql_api/types/mutation/mutation.graphql
- apps/codecov-api/graphql_api/types/mutation/mutation.py
- apps/codecov-api/graphql_api/types/mutation/sync_repos/__init__.py
- apps/codecov-api/graphql_api/types/mutation/sync_repos/sync_repos.graphql
- apps/codecov-api/graphql_api/types/mutation/sync_repos/sync_repos.py
- apps/codecov-api/services/repo_providers.py
This change makes the sync task use an app token rather than the user's token. It's a separate mutation, so it shouldn't conflict with the existing sync trigger.
Just also note that the `current_owner` is set to be the org with the JWT middleware: https://github.com/codecov/umbrella/blob/3541fdac533c9542505ab97d5ce5855db61278bd/apps/codecov-api/codecov_auth/middleware.py#L200.
> Add a new GraphQL mutation to sync with app token

- tools/devenv/Makefile.devenv
When starting our development environment and we run migrations we end up with multiple orphaned containers. This change prevents orphans from being created and cleans them up in the `make devenv.stop` command if a developer starts an orphan on their own.
> chore: Remove orphaned development containers

- apps/codecov-api/utils/logging_configuration.py
- apps/codecov-api/utils/tests/unit/test_logging.py
- apps/worker/helpers/log_context.py
- apps/worker/helpers/tests/unit/test_log_context.py
- libs/shared/shared/utils/sentry.py
- libs/shared/tests/unit/utils/test_sentry.py
Will also be using this for upload breadcrumbs
> feat(shared): Sentry utils to deduplicate

- apps/codecov-api/graphql_api/tests/test_test_analytics.py
- apps/codecov-api/graphql_api/types/test_results_aggregates/test_results_aggregates.py
- apps/codecov-api/utils/test_results.py
in the old TA implementation the possible outcomes were: pass, fail, and skip.
flaky failures were a subset of fails which meant we shouldn't include the
flaky_fail_count in the total tests calculation
In the new implementation that's not the case, flakiness is represented by the
outcome of a testrun, which means that we have to count flaky fails in the total
tests
This commit also does some light refactoring of the polars aggregation
expressions for simplicity, and fixes a bug where we weren't running fill_nan
when it was needed.
> fix: take flaky_fail_count into account for total tests in new TA impl

- apps/codecov-api/api.sh
- apps/codecov-api/migrate-timeseries.sh
- apps/codecov-api/migrate_timeseries.py
- apps/worker/migrate_timeseries.py
- tools/devenv/Makefile.devenv
* Adds the migrate scripts to both worker and API, and keep them in sync
* API runs timeseries migrations via the safer script (versus the unsafe migrate command)
* Rename devenv command for better correctness
> chore: Migrations refactor

- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query__0.json
- apps/codecov-api/graphql_api/tests/test_flake_aggregates_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_analytics_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_results_aggregates_timescale.py
- apps/codecov-api/utils/timescale_test_results.py
the previous implementation of calculating TA aggregates relied on a polars
file stored in GCS that contained all the testrun data for a branch in a repo
grouped by test and day. We would aggregate that data further according to the
user's desired time interval and group by test only. We would also calculate
aggregates on all of the data grouped only by repo.
grouped by repo, test, day -> filter by interval -> group by repo, test -> table
-> filter by interval -> group by repo -> aggregates
generating this cache file meant that we'd have to scan all rows in Timescale
related to the (branch, repo) combination in the relevant table. These queries
take long and the bottleneck is in reading all the rows from disk, especially if
the data is cold.
What if we could avoid these expensive queries …
> feat: fetch TA GQL data directly from Timescale

- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_test_results_timescale__0.json
- apps/codecov-api/graphql_api/tests/snapshots/flake_aggregates_timescale__TestFlakeAggregatesTimescale__gql_query_flake_aggregates_timescale__0.json
- apps/codecov-api/graphql_api/tests/snapshots/results_aggregates_timescale__TestTestResultsAggregatesTimescale__gql_query_test_results_aggregates_timescale__0.json
- apps/codecov-api/graphql_api/tests/test_flake_aggregates_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_analytics.py
- apps/codecov-api/graphql_api/tests/test_test_analytics_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_results_aggregates_timescale.py
- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
- apps/codecov-api/graphql_api/types/test_results/test_results.py
- apps/codecov-api/utils/test_results.py
See https://github.com/codecov/umbrella/pull/311 for more context
Adding code here to use the new code that fetches TA data directly from
timescale rather than the cache files in GCS. I'm putting it behind the feature
flag because we want to start by rolling this out to ourselves only. We still
want newer users to use Timescale through the cache files though so that's why
I made the changes to `use_new_impl`.
There's also some changes with regards to
the start date and end date, this is for our own sake, since there was some
confusion about what range of days we're getting data for. This is a product
related decision, not a technical decision and has to do with the fact that the
"last day" interval should really mean the last 24 hours, but we don't support
> feat: use direct from Timescale TA GQL aggregates behind feature flag

- libs/shared/shared/django_apps/upload_breadcrumbs/models.py
- libs/shared/shared/django_apps/upload_breadcrumbs/tests/test_models.py
Simplifies class usages elsewhere without changing the data that is  saved to the database.
> chore: Allow `None` inputs for `BreadcrumbData`

- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
i made this change to avoid some circular imports during testing where the timescale_test_results module wouldn't have to import any GQL types but i forgot to make the matching change in the code that calls get_test_results_queryset so this fixes the parameters being applied
> fix: get_test_results_queryset expects str for the parameter

- libs/shared/shared/django_apps/ta_timeseries/migrations/0018_create_repo_summary_caggs.py
- libs/shared/shared/django_apps/ta_timeseries/migrations/0019_refresh_repo_summary_caggs.py
- libs/shared/shared/django_apps/ta_timeseries/models.py
Fixes CCMRG-1376
The 2 PRs below have more context
https://github.com/codecov/umbrella/pull/311
https://github.com/codecov/umbrella/pull/317
With this change we're trying to avoid recomputing the repo-wide top of the page
aggregates. By using continuous aggregates here we can reduce the number of rows
we have to read to finalize the computation of the aggregates by a factor of the
number of tests in the repo, of course at the cost of some more intermediate
storage and asynchronous compute. By doing this we'll reduce the load we're
putting on the database every time a user goes to the dashboard.
We're choosing to use hierarchical continuous aggregates:
https://docs.tigerdata.com/use-timescale/latest/continuous-aggregates/hierarchical-continuous-aggregates/
This is so materializing the …
> feat: add new continuous aggregates to compute repo wide aggregates

- apps/codecov-api/codecov_auth/admin.py
- apps/codecov-api/codecov_auth/tests/test_admin.py
This PR aims to fix an issue where you are already logged into codecov with a provider different than the provider you are requesting to impersonate. Currently we'll just spin trying to find the default username which doesn't exist on the provider we are logged in as prior to impersonating, but now we'll redirect to the impersonated user's account directly.
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, …
> fix: Add username to impersonation request

- apps/codecov-api/upload/views/base.py
- apps/codecov-api/upload/views/bundle_analysis.py
- apps/codecov-api/upload/views/commits.py
- apps/codecov-api/upload/views/empty_upload.py
- apps/codecov-api/upload/views/legacy.py
- apps/codecov-api/upload/views/test_results.py
- apps/codecov-api/upload/views/transplant_report.py
- apps/codecov-api/upload/views/upload_completion.py
- apps/codecov-api/upload/views/upload_coverage.py
Reverts a [change I made a while ago](https://github.com/codecov/umbrella/commit/4ba094771448c393f44104673e65372880d7e6c4) to make `ShelterMixin` inherit from `View` and replaces it with proper mixin typing using protocols as suggested by `mypy`.
> fix(api): Proper typing for mixins

- apps/codecov-api/graphql_api/tests/test_flake_aggregates_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_results_aggregates_timescale.py
- apps/codecov-api/utils/timescale_test_results.py
Fixes CCMRG-1377
Depends on:
https://github.com/codecov/umbrella/pull/335
see:
https://github.com/codecov/umbrella/pull/311
https://github.com/codecov/umbrella/pull/317
https://github.com/codecov/umbrella/pull/319
we're going to use the repo wide CAs to populate some of the data here. We can't
use them for all of the data we want to return in the API so we'll have to fall
back to the testrun branch summaries for those ones: flake_count and
unique_test_count which is subsequently used in the calculation of slow tests
duration.
the continuous aggregates only rollup raw testrun data at a branch level
granularity for certain branches. For branches that aren't being rolled up we
can't fetch the data from CAs, instead we have to aggrgate directly from the
testrun hypertable.
We don't have to …
> feat: use new repo wide CAs in GQL API

- apps/worker/services/cleanup/repository.py
Fixes https://codecov.sentry.io/issues/6549361454/?project=4165036&query=is%3Aunresolved%20trace%3A37f1d2bb4969402da3709c31ff58ced3&referrer=issue-stream
Repo deletes after the first one were failing because we are trying to create a shadow owner that already exists.
> fix: Repo deletion fails for subsequent deletes on a single owner

- apps/codecov-api/upload/tests/test_upload.py
- apps/codecov-api/upload/tests/test_upload_download.py
- apps/codecov-api/upload/tests/views/test_reports.py
- apps/codecov-api/upload/tests/views/test_upload_coverage.py
- apps/codecov-api/upload/views/legacy.py
- apps/codecov-api/upload/views/reports.py
- apps/codecov-api/upload/views/upload_coverage.py
- apps/worker/tasks/preprocess_upload.py
- apps/worker/tasks/tests/unit/test_preprocess_upload.py
- libs/shared/shared/django_apps/upload_breadcrumbs/models.py
* Upload breadcrumbs for create report step
* Added to create report, coverage upload, and legacy endpoint uploads
* Added to pre-process upload worker task
* Simplified some view logic so that returning method not allowed is not necessary and is handled by the rest framework library automatically
> feat: Upload breadcrumbs for create report

- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_test_results_timescale_branch__0.json
- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_test_results_timescale_non_precomputed_branch__0.json
- apps/codecov-api/graphql_api/tests/test_flake_aggregates_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_analytics_timescale.py
- apps/codecov-api/graphql_api/tests/test_test_results_aggregates_timescale.py
- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
- apps/codecov-api/utils/timescale_test_results.py
Fixes CCMRG-1395
the continuous aggregates only rollup raw testrun data at a branch level
granularity for certain branches. For branches that aren't being rolled up we
can't fetch the data from CAs, instead we have to aggrgate directly from the
testrun hypertable.
We don't have to compute test results aggregates or flake aggregates yet, as
that adds too much complexity for now, and we'll probably test out a new CA
where we compute rollups for all branches before we build that.
> fix: aggregate test results from TA hypertable if data's not in CAs

- apps/codecov-api/codecov_auth/authentication/types.py
- apps/codecov-api/upload/tests/test_upload.py
- apps/codecov-api/upload/tests/views/test_empty_upload.py
- apps/codecov-api/upload/tests/views/test_upload_completion.py
- apps/codecov-api/upload/tests/views/test_upload_coverage.py
- apps/codecov-api/upload/tests/views/test_uploads.py
- apps/codecov-api/upload/views/bundle_analysis.py
- apps/codecov-api/upload/views/commits.py
- apps/codecov-api/upload/views/empty_upload.py
- apps/codecov-api/upload/views/legacy.py
- apps/codecov-api/upload/views/reports.py
- apps/codecov-api/upload/views/test_results.py
- apps/codecov-api/upload/views/transplant_report.py
- apps/codecov-api/upload/views/upload_completion.py
- apps/codecov-api/upload/views/upload_coverage.py
- apps/codecov-api/upload/views/uploads.py
- libs/shared/shared/django_apps/upload_breadcrumbs/models.py
- libs/shared/shared/django_apps/upload_breadcrumbs/tests/test_models.py
- libs/shared/shared/upload/utils.py
* Added breadcrumbs on the API side for
* Waiting on coverage upload: legacy (now complete), coverage upload (now complete), and upload endpoints
* Notifications triggered: empty upload and upload completion endpoints
* Added more predefined upload breadcrumb errors
* Typing improvements for multiple upload-related files
> feat(api): Upload breadcrumbs for waiting on coverage upload and notifications triggered

- apps/codecov-api/graphql_api/helpers/mutation.py
- apps/codecov-api/graphql_api/helpers/tests/test_mutation.py
This PR introduces a conditional that allows us to bypass the requires_authentication middleware when we're coming from the Sentry app. This will allow us to run GQL mutations from the Sentry app using the new sentry GQL endpoint wrapper.
Also adds some UTs
> fix: allow bypass of auth when coming from sentry with jwt

- README.md
- docker-compose.yml
- tools/devenv/Makefile.devenv
* Proxies the local Django admin interface so that it can be accessed in development (depends on https://github.com/codecov/codecov-gateway/pull/125)
* Adds a make command to make a user an admin
> feat(devenv): Django admin now works locally

- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query__0.json
- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_testsuites_and_flags_resolvers__0.json
- apps/codecov-api/graphql_api/tests/snapshots/analytics_timescale__TestAnalyticsTestCaseNew__gql_query_testsuites_and_flags_resolvers_with_term__0.json
- apps/codecov-api/graphql_api/tests/test_test_analytics.py
- apps/codecov-api/graphql_api/tests/test_test_analytics_timescale.py
- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
- apps/codecov-api/utils/test_results.py
- apps/worker/services/test_analytics/tests/test_ta_cache_rollups.py
- apps/worker/tasks/cache_test_rollups.py
- apps/worker/tasks/tests/unit/test_cache_test_rollups.py
this commit contains both API and worker changes
the worker change is that we're no longer caching rollups from timescale if the impl type passed to the cache rollup task is new or both
the reason for this is that the queries done against timescale to load the rollups are way too expensive and it's causing DB issues
because we're no longer updating the rollups we need users that were previously reading from those rollups to read directly from timescale instead which is what the API changes consist of.
We're creating "direct from Timescale" implementations of the TA testsuites and flags resolvers and we're changing the condition for the new implementation to check both the READ_NEW_TA feature flag and the use new impl function
> fix: stop populating cache files and new repos read from timescale

- apps/worker/tasks/tests/unit/test_base.py
- libs/shared/shared/celery_config.py
Bumps the default soft time limit to 600s and hard time limit to 720s to match our Helm chart defaults that are being removed.
> chore: Bump default soft and hard time limit values

- apps/worker/database/models/core.py
- apps/worker/services/processing/intermediate.py
- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
- apps/worker/tasks/upload_finisher.py
* Breadcrumbs on the last of the three main upload tasks
* Resolved deprecation notice of the Redis command by moving to the suggested alternative
* Resolved datetime deprecation and timezone warnings
* Also brings the SQLAlchemy models in line with the Django models
> feat(worker): Upload breadcrumbs for upload finisher task

- libs/shared/shared/django_apps/ta_timeseries/migrations/0024_create_test_aggregate_daily_cas.py
- libs/shared/shared/django_apps/ta_timeseries/migrations/0029_add_retention_policies_to_new_caggs.py
we add if not exists so the migrations don't fall over if they were previously
partially applied
we add with no data so it doesn't refresh data on CA creation
also adds retention policies to new CAs in a separate migration
> fix: new timescale CA definitions

- apps/codecov-api/upload/helpers.py
- apps/codecov-api/upload/tests/test_helpers.py
- apps/codecov-api/upload/views/legacy.py
- apps/worker/tasks/base.py
- apps/worker/tasks/tests/unit/test_base.py
- apps/worker/tasks/tests/unit/test_upload_finisher_task.py
- apps/worker/tasks/tests/unit/test_upload_processing_task.py
- apps/worker/tasks/upload_finisher.py
- apps/worker/tasks/upload_processor.py
Fixes the case where an exception is thrown without a message and so `str(exception)` returns just an empty string. Example [here](https://codecov.sentry.io/issues/6792055653/events/b145499872ec44fbb87a5ec7d049185f/) from [this exception](https://codecov.sentry.io/issues/6792055621/events/c5e41511c6ee4589a1537247b2f6854d/)
> fix: Use `repr` for unknown upload breadcrumb errors

- apps/worker/tasks/notify.py
Warning was `SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly: .filter(UploadError.upload_id.in_(ta_upload_ids))`
[GCP logs for frequency](https://cloudlogging.app.goo.gl/jcp7pHf1DpBT7hQRA)
> fix(worker): Resolve noisy SQLAlchemy warning

- apps/codecov-api/codecov/settings_base.py
- libs/shared/shared/django_apps/settings_test.py
- libs/shared/shared/django_apps/upload_breadcrumbs/admin.py
- libs/shared/shared/django_apps/upload_breadcrumbs/templates/admin/upload_breadcrumbs/uploadbreadcrumb/change_list.html
- libs/shared/shared/django_apps/upload_breadcrumbs/tests/test_admin.py
As the title says, this PR introduces an admin view for upload breadcrumbs. Photos below:
> feat(admin): Admin view for upload breadcrumbs

- libs/shared/shared/django_apps/utils/partitioning.py
Allows for either unlimited retention or a retention policy based on years, months, and/or days. Defaults to the current value of 90 days.
> feat(shared): Config options for upload breadcrumbs retention period

- apps/codecov-api/api/public/v2/tests/test_api_coverage_viewset.py
- apps/codecov-api/graphql_api/tests/test_bundle_analysis_measurements.py
- apps/codecov-api/graphql_api/tests/test_components.py
- apps/codecov-api/graphql_api/tests/test_flags.py
- apps/codecov-api/timeseries/tests/test_helpers.py
- ci-tests.docker-compose.yml
- docker-compose.yml
- libs/shared/shared/django_apps/migration_utils.py
- libs/shared/shared/django_apps/ta_timeseries/migrations/0030_add_testrun_repo_test_time_idx.py
- libs/shared/shared/django_apps/ta_timeseries/migrations/0031_redefine_test_aggregate_dailies_by_test_id.py
- libs/shared/shared/django_apps/ta_timeseries/models.py
there's no index currently covering the testsuite, classname and name fields, and we don't want to create an index on those fields because names can be long, so we should group by test_id, because an index already exists
> fix: redefine new CAs to group by test_id

- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/views/github.py
- libs/shared/shared/github/__init__.py
We're essentially treating Sentry apps like the custom ones that are defined through the database, by including the app id and pem path when creating the DB object in the webhook handler.
we're trusting that the logic that was written for supporting those custom apps defined through the DB works properly and with that assumption, this approach should work.
> fix: update webhook github app installation handling

- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
not ordering is causing flaky tests. We might as well order the results so it's easier for users to navigate as well
> fix: order testsuites and flags in GQL API (also fixes test flakiness)

- apps/codecov-api/api/sentry/tests/test_views.py
- apps/codecov-api/api/sentry/views.py
This PR updates the account link code to use the new sentry merge plan rather than the default plan since that's the one we'll be using for now to determine which users are sentry account users.
Relates to https://linear.app/getsentry/issue/CCMRG-1331/sentry-hook-into-sentry-github-app-install-to-call-codecov
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my contributions, …
> fix: Update plan when calling account link endpoint

- apps/codecov-api/webhook_handlers/helpers.py
- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/tests/test_helpers.py
- apps/codecov-api/webhook_handlers/tests/test_sentry.py
- apps/codecov-api/webhook_handlers/views/github.py
- apps/codecov-api/webhook_handlers/views/sentry.py
if we receive a sentry webhook for an installation where we know the  owner is not linked to a sentry or vice versa, we want to block  processing that webhook
this is to avoid double processing webhooks: if a user has linked their  sentry account then we only need to process their sentry webhooks and  ignore webhooks that come from the codecov app
> feat: only process webhook if account associated with service

- apps/worker/tasks/sync_pull.py
- apps/worker/tasks/tests/unit/test_sync_pull.py
we made a change a while ago where the process flakes task consumes from a list in redis and we forgot to push the commit sha onto that list when we queue up the task in the sync pulls task
> fix: sync pull task calling process flakes task

- apps/worker/services/test_analytics/ta_timeseries.py
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__2.txt
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__3.txt
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__4.txt
- apps/worker/tasks/notify.py
- apps/worker/tasks/tests/integration/test_notify_task.py
- apps/worker/tasks/tests/unit/snapshots/notify_task__TestNotifyTask__ta_relevant_context__0.txt
- apps/worker/tasks/tests/unit/test_notify_task.py
with the recent rollout of timescale based TA we want to fully use the timescale TA models, i missed updating the notify task so im updating it now
> feat: use testrun models in notify task instead of old TA models

- apps/worker/helpers/ta_status.py
- apps/worker/helpers/tests/test_ta_status.py
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__2.txt
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__3.txt
- apps/worker/services/test_analytics/tests/snapshots/ta_finish_upload__ta_finish_upload__4.txt
- apps/worker/services/test_analytics/tests/test_ta_finish_upload.py
- apps/worker/tasks/notify.py
- apps/worker/tasks/tests/unit/test_notify_task.py
we need to make sure we don't try getting data from the TA database is TA is not enabled for the entire codecov instance, which I wasn't doing.
I also do some light refactoring of the source code and the tests.
entry's choice of terms.
> fix: don't check TA if TA is disabled in notify

- apps/codecov-api/webhook_handlers/tests/test_github.py
- apps/codecov-api/webhook_handlers/tests/test_sentry.py
- apps/codecov-api/webhook_handlers/views/github.py
- libs/shared/shared/django_apps/codecov_auth/models.py
- libs/shared/tests/unit/django_apps/codecov_auth/test_codecov_auth_models.py
the code was previously not setting the name correctly. This isn't the greatest
approach since we're handling the sentry github app case specifically and
ideally we'd have a "system" for discerning between "default apps" and
"custom apps" but for now this hard coded handling will have to do.
This commit also updates the logic to no longer set the pem path (because it's
no longer needed) and to make that possible without breaking the existing
behaviour we have to update the definition of the is_configured method on the
github app installation model so it considers a list of default app IDs instead
of just the one.
> fix: sentry github app installation logic

- apps/codecov-api/billing/helpers.py
This PR fixes https://codecov.sentry.io/issues/6818916968/?environment=production&project=5215654&query=is%3Aunresolved%20billing&referrer=issue-stream which occurs when owners.admins is None.
Owners.admins can either be None of an iterable with at least 1 element, and set.update() requires a non-None value to work
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to my contributions, and by keeping this boilerplate intact I confirm that Sentry can use, modify, copy, and redistribute my …
> fix: Add guard incase admin object is None

- apps/worker/services/test_analytics/ta_finish_upload.py
- apps/worker/services/test_analytics/tests/test_ta_finish_upload.py
we're currently always making the all tests passed comment, even when there haven't already been failures, which is not the goal of this comment, it's there to wipe away the failed tests comment for users only using TA and not coverage.
To achieve this i'm making it so we can only make the all tests passed comment if we've already made some comment. We have to queue the notify afterwards because it's possible we have a coverage comment that we're editing and we've accidentally overwritten that
> feat: only make all tests passed comment after the failed tests comment

- apps/codecov-api/graphql_api/tests/snapshots/flake_aggregates_timescale__TestFlakeAggregatesTimescale__gql_query_flake_aggregates_timescale__0.json
- apps/codecov-api/graphql_api/tests/snapshots/results_aggregates_timescale__TestTestResultsAggregatesTimescale__gql_query_test_results_aggregates_timescale__0.json
- apps/codecov-api/graphql_api/types/test_analytics/test_analytics.py
we needed to update the UI to always pass the branch param, even when  the branch is the default branch, and now that that is done, we can  safely set the default here to be “all branches"
also refs the measurement interval code in test analytics
> feat: restore TA GQL resolvers to defaulting to all branches

- apps/codecov-api/api/sentry/tests/test_views.py
- apps/codecov-api/api/sentry/urls.py
- apps/codecov-api/api/sentry/views.py
Updates the perm classes to none because the Sentry JWT auth covers authentication, and this route isn't exposed in sentry
> fix: Perm classes for account link/unlink endpoints

- libs/shared/shared/helpers/github_apps.py
we were making it so users that used the github_enterprise config option weren't able to use the github app
> fix: include github_enterprise config option in default app IDs

- apps/codecov-api/api/sentry/tests/test_views.py
- apps/codecov-api/api/sentry/views.py
This PR aims to fix a bug where user who were installing the sentry GH app and having an account linked were inadvertently having their seat counts set to 1 due to the Account being the source of truth for seats if one exists.
We will now look to see if the owner having an account created for them has seats already and use that, and if there are multiple owners, to use the one with the most amount of seats. 
Also gets rid of a bunch of AI comments
Look, I get it. The entity doing business as "Sentry" was incorporated in the State of Delaware in 2015 as Functional Software, Inc. In 2022 this entity acquired Codecov and as result Sentry is going to need some rights from me in order to utilize my contributions in this PR. So here's the deal: I retain all rights, title and interest in and to …
> fix: Account link should respect existing owners seat counts

- apps/worker/services/test_results.py
- apps/worker/services/tests/snapshots/results__build_message_for_prevent__0.txt
- apps/worker/services/tests/test_test_results.py
we previously weren't able to do this because the link required having access to an ID that is specific to Sentry Integrations, but now we can because the link uses the name of the github org instead.
we generate the link by using the Account name which maps to the sentry account's name, the owner's name, which maps to the github org's name and the repo name and branch names.
> feat: add TA dashboard link to prevent comments
